openapi: "3.0.0"

paths:
  /check-by-addresses:
    get:
      summary: Check by addresses (full match)
      description: Checks if contract with the desired chain and address is verified and in the repository.
      parameters:
        - name: addresses
          in: query
          description: The addresses of the contracts.
          required: true
          schema:
            type: string
            format: validate-addresses
        - name: chainIds
          in: query
          description: The IDs of the chains.
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful Response
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    address:
                      type: string
                    status:
                      type: string
                    chainIds:
                      type: array
                      items:
                        type: string
