openapi: "3.0.0"

paths:
  /files/any/{chain}/{address}:
    get:
      summary: Get file tree
      description: Returns repository URLs for every file in the source tree for the desired chain and address. Searches for full and partial matches.
      tags:
        - Repository
      parameters:
        - name: chain
          in: path
          required: true
          schema:
            type: string
        - name: address
          in: path
          required: true
          schema:
            type: string
            format: validate-addresses
      responses:
        "200":
          description: Successful response. Returns a list of files and the status of the match (full or partial).
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    enum: [full, partial]
                  files:
                    type: array
                    items:
                      type: string
                      format: uri
        "404":
          description: Contract is not available in the repository.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
