version: "3.3"
services:
  https-portal:
    env_file:
    - .env.prod
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: '${FQDN} -> http://ui:1234, server.${FQDN} -> http://server:80, repository.${FQDN} -> http://respository:80'
      STAGE: 'staging'
    container_name: nginx
    volumes:
    - repository:/var/www/vhosts/repository.source-verify.blockchain-it.hr
    - ./nginx.conf:/etc/nginx/conf.d/source-verify.blockchain-it.hr.ssl.conf
    networks:
      - source-verify-network
  monitor:
    image: blockchainit/source-verify-monitor:${TAG}
    env_file:
    - .env.prod
    container_name: monitor
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
    networks:
    - source-verify-network
    restart: always
  ui:
    image: blockchainit/source-verify-ui:${TAG}
    env_file:
    - .env.prod
    container_name: ui
    ports:
    - "${UI_EXTERNAL_PORT}:${UI_PORT}"
    networks:
    - source-verify-network
    restart: always
  server:
    image: blockchainit/source-verify-server:${TAG}
    env_file:
    - .env.prod
    container_name: server
    ports:
    - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    networks:
    - source-verify-network
    restart: always
  repository:
    image: mythevalentinus/h5ai-nginx:latest
    environment:
      USERNAME: user
      PASSWORD: pass
    restart: always
    container_name: repository
    volumes:
      - h5ai:/h5ai
      - ./repository:/data
      - ./h5ai-nginx/options.json:/h5ai/_h5ai/private/conf/options.json
      - ./h5ai-nginx/types.json:/h5ai/_h5ai/private/conf/types.json
    ports:
    - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
networks:
  source-verify-network:
volumes:
  repository:
  db:
  h5ai:
    driver: local
 
