version: "3.3"
services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: 'source-verify.blockchain-it.hr -> http://ui:1234, monitor.source-verify.blockchain-it.hr -> http://monitor:80, server.source-verify.blockchain-it.hr -> http://server:80, backup.source-verify.blockchain-it.hr -> http://server:80' #have here resources serving directly 
      STAGE: 'staging'
    container_name: nginx
    networks:
      - source-verify-network
  monitor:
    env_file:
     - .env.production
    container_name: monitor
    build:
      context: .
      dockerfile: Dockerfile.monitor
    ports:
    - "3000:80"
    networks:
    - source-verify-network
    restart: always
  ui:
    env_file:
     - .env.production
    container_name: ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
    - "1234:1234"
    networks:
    - source-verify-network
    restart: always
  server:
    env_file:
     - .env.production
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
    - "10000:80"
    networks:
    - source-verify-network
    restart: always
  # health-check:
  #   container_name: health-check
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.healthcheck
  #   ports:
  #     - "10000:80"
  #   networks:
  #     - source-verify-network
  #   restart: always
networks:
  source-verify-network:
