version: "3.3"
services:
  https-portal:
    env_file:
    - .env.prod
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      DOMAINS: '${FQDN} -> http://ui:1234, monitor.${FQDN} -> http://monitor:80, server.${FQDN} -> http://server:80, backup.${FQDN} -> http://nginx:80, ${FQDN}/repository -> http://nginx:80' #have here resources serving directly 
      STAGE: 'staging'
    container_name: nginx
    networks:
      - source-verify-network
  monitor:
    image: blockchainit/source-verify-monitor:${TAG}
    env_file:
    - .env.prod
    container_name: monitor
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
    networks:
    - source-verify-network
    restart: always
  ui:
    image: blockchainit/source-verify-ui:${TAG}
    env_file:
    - .env.prod
    container_name: ui
    ports:
    - "${UI_EXTERNAL_PORT}:${UI_PORT}"
    networks:
    - source-verify-network
    restart: always
  server:
    image: blockchainit/source-verify-server:${TAG}
    env_file:
    - .env.prod
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
    - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    networks:
    - source-verify-network
    restart: always
  nginx:
    image: nginx:stable
    container_name: nginx
    ports: 
    - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
    volumes:
    - repository:/usr/share/nginx/html
    - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  source-verify-network:
volumes:
  repository:
  db:
