version: "3.3"
services:
  monitor:
    image: ethereum/source-verify:monitor-${TAG}
    env_file:
    - .env.${TAG}
    container_name: monitor
    build:
      context: .
      dockerfile: src/Dockerfile.monitor
    ports:
    - "${MONITOR_EXTERNAL_PORT}:${MONITOR_PORT}"
    restart: always
    volumes:
    - ./repository:/app/repository
  ui:
    image: ethereum/source-verify:ui-${TAG}
    env_file:
    - .env.${TAG}
    container_name: ui
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
    - "${UI_EXTERNAL_PORT}:${UI_PORT}"
    restart: always
  server:
    image: ethereum/source-verify:server-${TAG}
    env_file:
    - .env.${TAG}
    container_name: server
    build:
      context: .
      dockerfile: src/Dockerfile.server
    ports:
    - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    volumes:
    - ./repository:/app/repository
    restart: always
  localchain:
    image: ethereum/source-verify:localchain-${TAG}
    env_file:
    - .env.${TAG}
    container_name: localchain
    build:
      context: .
      dockerfile: src/Dockerfile.localchain
    ports:
    - "${LOCALCHAIN_EXTERNAL_PORT}:${LOCALCHAIN_PORT}"
    restart: always
  repository:
    image: ethereum/source-verify:repository-${TAG}
    build:
      context: h5ai-nginx
      dockerfile: Dockerfile
    restart: always
    container_name: repository
    volumes:
      - h5ai:/h5ai
      - ./repository:/data
      - ./h5ai-nginx/options.json:/h5ai/_h5ai/private/conf/options.json
      - ./h5ai-nginx/types.json:/h5ai/_h5ai/private/conf/types.json
    ports:
    - ${NGINX_EXTERNAL_PORT}:${NGINX_PORT}
volumes:
  repository:
  db:
  h5ai:
    driver: local
