openapi: "3.0.0"
info:
  version: 1.0.0
  title: Sourcify API
  description: APIs to interact with Sourcify
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://{base_url}
    variables:
      base_url:
        default: localhost:5555
        description: server
paths:
  /session/data:
    $ref: "src/server/controllers/verification/create2/session/create2.yaml#/paths/~1session~1data"
  /verify:
    $ref: "src/server/controllers/verification/verify/stateless/verify.stateless.paths.yaml#/paths/~1verify"
  /verify/solc-json:
    $ref: "src/server/controllers/verification/solc-json/stateless/solc-json.stateless.paths.yaml#/paths/~1verify~1solc-json"
  /session/input-solc-json:
    $ref: "src/server/controllers/verification/solc-json/session/solc-json.session.paths.yaml#/paths/~1session~1input-solc-json"
