version: "3.7"
services:
  ui-draft:
    image: ethereum/source-verify:ui-draft-${TAG}
    build:
      context: ../ui-draft
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - REACT_APP_SERVER_URL=${SERVER_URL}
      - REACT_APP_REPOSITORY_URL=${REPOSITORY_URL}
