version: "3.7"
services:
  ui-draft:
    image: ethereum/source-verify:ui-draft-${TAG}
    build:
      context: ../ui-draft
      dockerfile: Dockerfile
      # Pass SERVER_URL and REPOSITORY_URL to be injected build time.
      # Will be set in .env (see scripts/build_and_publish_docker_images.sh)
      args:
        - SERVER_URL=$SERVER_URL
        - REPOSITORY_URL=$REPOSITORY_URL
        - IPNS=$IPNS
