version: "3.7"

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify
  labels:
    - "autoheal=true" # Label to trigger autoheal for this service

networks:
  source-verify:

services:
  server:
    <<: *project-base
    image: ethereum/source-verify:server-${TAG}
    container_name: server-${TAG}
    ports:
      - "${SERVER_EXTERNAL_PORT}:${SERVER_PORT}"
    volumes:
      - type: bind
        source: $REPOSITORY_PATH_HOST
        target: $REPOSITORY_PATH
      - type: bind
        source: $SOLC_REPO_HOST
        target: $SOLC_REPO
      - type: bind
        source: $SOLJSON_REPO_HOST
        target: $SOLJSON_REPO
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${SERVER_PORT}/health"]
      interval: 30s
      timeout: 10s
      retries: 10

  autoheal:
    image: willfarrell/autoheal
    environment:
      - AUTOHEAL_CONTAINER_LABEL=autoheal # Set to 'autoheal' to only heal containers with the 'autoheal=true' label
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
