version: "3.7"

networks:
  source-verify:

x-project-base: &project-base
  env_file:
    - .env
  restart: always
  networks:
    - source-verify

services:
  ui-legacy:
    <<: *project-base
    image: ethereum/source-verify:ui-legacy-${TAG}
    container_name: ui-legacy-${TAG}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${UI_PORT}"]
      interval: 30s
      timeout: 10s
      retries: 10
    ports:
      - "${UI_LEGACY_EXTERNAL_PORT}:1234"
