version: 2.1

# Parameter that can be passed in this pipeline have to be defined here too. Used with nightly.
parameters:
  run-nightly:
    type: boolean
    default: false

aliases:
  - &monitor-e2e-base
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: checkout metacoin-source-verify
          command: cd ~/project && git clone git@github.com:sourcifyeth/metacoin-source-verify.git
      - run:
          name: install
          command: cd ~/project/metacoin-source-verify && npm ci
      - run:
          name: monitor test
          command: cd ~/project/metacoin-source-verify && ./scripts/monitor_e2e.sh
          no_output_timeout: 30m
    docker:
      - image: cimg/node:16.15
  - &verification-e2e-base
    steps:
      - run:
          name: Avoid hosts unknown for github
          command: mkdir ~/.ssh/ && echo -e "Host github.com\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
      - run:
          name: checkout metacoin-source-verify
          command: cd ~/project && git clone git@github.com:sourcifyeth/metacoin-source-verify.git
      - run:
          name: install
          command: cd ~/project/metacoin-source-verify && npm ci
      - run:
          name: verification test
          command: cd ~/project/metacoin-source-verify && ./scripts/verification_e2e.sh
    docker:
      - image: cimg/node:16.15

workflows:
  e2e-tests:
    jobs:
      - monitor-e2e-goerli
      - monitor-e2e-sepolia
      - verification-e2e-goerli
      - verification-e2e-sepolia
  s3-backup-check:
    jobs:
      - check-s3-backup
  etherscan-instances:
    jobs:
      - check-etherscan-instances

jobs:
  monitor-e2e-goerli:
    <<: *monitor-e2e-base
    environment:
      CHAIN_ID: 5
      CHAIN_NAME: goerli
  monitor-e2e-sepolia:
    <<: *monitor-e2e-base
    environment:
      CHAIN_ID: "11155111"
      CHAIN_NAME: sepolia
  verification-e2e-goerli:
    <<: *verification-e2e-base
    environment:
      CHAIN_ID: 5
      CHAIN_NAME: goerli
  verification-e2e-sepolia:
    <<: *verification-e2e-base
    environment:
      CHAIN_ID: "11155111"
      CHAIN_NAME: sepolia
  check-s3-backup:
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install @aws-sdk/client-s3
      - run:
          name: backup test
          command: node --experimental-fetch ./scripts/check-s3-backup.mjs
    docker:
      - image: cimg/node:16.15
  check-etherscan-instances:
    working_directory: ~/source-verify
    steps:
      - checkout
      - run:
          name: install dependencies
          command: npm install
      - run:
          name: build
          command: npx lerna run build
      - run:
          name: test
          command: cd ./services/server && npx mocha test/etherscan/etherscanInstances.js --exit
    docker:
      - image: cimg/node:16.15
