version: 2.1

# Must use setup as we use continuation
setup: true 

# Parameter that can be passed in this pipeline have to be defined here too.
parameters:
  run-nightly:
    type: boolean
    default: false

orbs:
  continuation: circleci/continuation@0.3.1

workflows:
  nightly:
    jobs:
      - continuation/continue:
          configuration_path: .circleci/e2e-tests.yml
