name: Feature Request
description: Feature verified project on sourcify landing page
title: "[Feature Request]: "
labels: ["feature", "support"]
assignees:
  - ogwurujohnson
  - kuzdogan
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: project
    attributes:
      label: Project Name
      description: Project name verified on sourcify
      placeholder: ex. uniswap
    validations:
      required: true
  - type: input
    id: network
    attributes:
      label: Verification Network
      description: Which network was this project verified
      placeholder: ex. Ethereum
    validations:
      required: true
  - type: input
    id: logo
    attributes:
      label: Project Logo
      description: Provide project logo URL
      placeholder: ex. https://uniswap-logo
    validations:
      required: true
