openapi: "3.0.0"

paths:
  /verify:
    post:
      description: |
        Sends provided files for verification
      tags:
        - Stateless Verification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - address
                - chain
                - files
              properties:
                address:
                  type: string
                  format: address
                chain:
                  type: string
                  format: supported-chainId
                files:
                  type: object
                creatorTxHash:
                  type: string
                chosenContract:
                  type: string
          multipart/form-data:
            schema:
              type: object
              required:
                - address
                - chain
              properties:
                address:
                  type: string
                  format: address
                chain:
                  type: string
                  format: supported-chainId
                files:
                  description: This field is required
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                    - type: string
                      format: binary
                    - type: array
                      items:
                        type: string
                        format: binary
                creatorTxHash:
                  type: string
                chosenContract:
                  type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../errors.yaml#/components/schemas/ContractNoDeploy"
                  - $ref: "../../errors.yaml#/components/schemas/ContractPerfect"
                  - $ref: "../../errors.yaml#/components/schemas/ContractPartial"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../errors.yaml#/components/schemas/MetadataNotFound"
                  - $ref: "../../errors.yaml#/components/schemas/BadFormattedJson"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "../../errors.yaml#/components/schemas/FilesNotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "../../errors.yaml#/components/schemas/ResourceMissing"
