openapi: "3.0.0"
paths:
  /session/data:
    get:
      description: |
        Returns all pets
      parameters:
        - name: type
          in: query
          description: maximum number of results to return
          required: true
          schema:
            type: string
            enum:
              - dog
              - cat
      responses:
        200:
          description: OK
