openapi: "3.0.0"

paths:
  /session/input-files:
    post:
      summary: Add input files
      tags:
        - Session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: object
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  description: This field is required
                  oneOf:
                    - type: string
                    - type: array
                      items:
                        type: string
                    - type: string
                      format: binary
                    - type: array
                      items:
                        type: string
                        format: binary
      parameters:
        - name: url
          in: query
          schema:
            type: string
            format: uri
          description: Remote file URL
          required: false
      responses:
        "200":
          description: Response is sent when the upload is successful under different conditions.
          content:
            application/json:
              schema:
                type: object
                properties:
                  contracts:
                    type: array
                    items:
                      type: object
                      properties:
                        compiledPath:
                          type: string
                        name:
                          type: string
                        compilerVersion:
                          type: string
                        verificationId:
                          type: string
                        status:
                          type: string
                        files:
                          type: object
                          properties:
                            found:
                              type: array
                              items:
                                type: string
                            missing:
                              type: array
                              items:
                                type: string
                  unused:
                    type: array
                    items:
                      type: string
        "413":
          description: |
            Response is sent when the session already takes up a lot of memory, 
            cannot hold a single new input file, and a new input file is being uploaded.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
