openapi: "3.0.0"

paths:
  /verify/create2:
    post:
      summary: Verify create2
      tags:
        - Stateless Verification
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                clientToken:
                  type: string
                  description: Mandatory client token to call this api
                deployerAddress:
                  type: string
                  format: address
                  description: The deployer addresses
                salt:
                  oneOf:
                    - type: string
                    - type: number
                abiEncodedConstructorArguments:
                  type: string
                  description: ABI encoded constructor arguments
                files:
                  type: object
                  additionalProperties:
                    type: string
                  description: An array of files
                create2Address:
                  type: string
                  format: address
                  description: The create2 address
              required:
                - deployerAddress
                - files
                - create2Address
                - salt
      responses:
        "200":
          description: The contract has been successfully checked or sourcified
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../errors.yaml#/components/schemas/ContractNoDeploy"
                  - $ref: "../../errors.yaml#/components/schemas/ContractPerfect"
                  - $ref: "../../errors.yaml#/components/schemas/ContractPartial"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../errors.yaml#/components/schemas/MetadataNotFound"
                  - $ref: "../../errors.yaml#/components/schemas/BadFormattedJson"
        "404":
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "../../errors.yaml#/components/schemas/FilesNotFound"
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "../../errors.yaml#/components/schemas/ResourceMissing"
                  - $ref: "../../errors.yaml#/components/schemas/Create2AddressMismatch"
