openapi: "3.0.0"

paths:
  /session/input-solc-json:
    post:
      summary: Verify solc-json
      tags:
        - Session
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                files:
                  type: object
                  additionalProperties:
                    type: string
                  description: 'Files to upload {"path/filename": "content"}'
                compilerVersion:
                  type: string
                  description: Compiler version
              required:
                - compilerVersion
                - files
      responses:
        "200":
          description: Successful operation
        "400":
          description: Invalid input
